name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
# Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
  

      - name: Configure project id
        run: |
          gcloud config set project us-gcp-ame-con-116-npd-1
      #Build and Push image
      - name: Build
        run: |
              docker build -t gcr.io/us-gcp-ame-con-116-npd-1/strava-service .
              
          # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
            gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push
        run: |
            docker push gcr.io/us-gcp-ame-con-116-npd-1/strava-service

      - name: Deploy
        run: |    
            gcloud run deploy strava-service --port=8084 --image gcr.io/us-gcp-ame-con-116-npd-1/strava-service --platform managed --region us-west2 --allow-unauthenticated --vpc-connector hu-conn --add-cloudsql-instances huex-mysql  
